/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
    public String getGreeting() {
        return "こんにちは　SEMonster";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Monster monster = new Monster(2, 2);
        Monster monster2 = new Monster(2, 3);
        System.out.print(monster.toString());
        System.out.print(monster2.toString());
    }
}
