/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;
import java.util.LinkedList;


public class App {
    public String getGreeting() {
        return "こんにちは　SEMonster";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Monster monster = new Monster(2, 2);
        Monster monster2 = new Monster(2, 3);
        Monster monster3 = new Monster(2, 4);
        System.out.print(monster.toString());
        System.out.print(monster2.toString());
        System.out.print(monster3.toString());
        LinkedList<Integer> randomNumberList = new LinkedList<>(); // 任意のランダム数値のリストを作成
        for (int i = 0; i < 20; i++) {
            randomNumberList.add(i % 5); // 0から4までの数値を追加
        }
        Player player = new Player(randomNumberList, "name"); // プレイヤー名は適宜指定してください
        player.drawMonsters();
        System.out.println(player.toString());
        System.out.println("残りhpは" + player.getHp());
    }
}
